# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LIA\LiaImageserver\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  LIA\LiaImageserver\Service\ImageService:
    public: true
